name: Export iOS
on:
  push:

jobs:
  export-ios:
    name: Export iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: "Download and Install Godot 4.1.3"
        continue-on-error: false
        shell: bash
        run: |
          # GODOT_HOME=$HOME/bin
          # GODOT_BIN=$GODOT_HOME/godot
          # mkdir -p $GODOT_HOME
          # chmod 770 $GODOT_HOME
          # GODOT_CONF_PATH=$HOME/.config/godot
          # if [ ! -d $GODOT_CONF_PATH ]; then
          #   mkdir -p $GODOT_CONF_PATH
          #   chmod 770 $GODOT_CONF_PATH
          # fi

          GODOT_VERSION=4.1.3
          # GODOT_PACKAGE=Godot_v$GODOT_VERSION-stable_macos.universal
          # wget https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/$GODOT_PACKAGE.zip -P ${{ runner.temp }}
          # unzip ${{ runner.temp }}/$GODOT_PACKAGE.zip -d $GODOT_HOME
          # mv $GODOT_HOME/$GODOT_PACKAGE $GODOT_BIN
          # chmod u+x $GODOT_BIN
          # echo "GODOT_HOME=$GODOT_HOME" >> "$GITHUB_ENV"
          # echo "GODOT_BIN=$GODOT_BIN" >> "$GITHUB_ENV"

          brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/4ed2983b312044fd39cd3d321dbadc30bef78e1e/Casks/g/godot.rb

          mkdir -v -p ~/.local/share/godot/export_templates
          GODOT_TEMPLATES_PACKAGE=Godot_v$GODOT_VERSION-stable_export_templates.tpz
          wget https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/$GODOT_TEMPLATES_PACKAGE -P ${{ runner.temp }}
          unzip ${{ runner.temp }}/$GODOT_TEMPLATES_PACKAGE -d ~/.local/share/godot/export_templates
          ls -la ~/.local/share/godot/export_templates
