name: Export
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        run: |
          mkdir -v -p build/web
          godot -v --export-release "web" build/web/index.html
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Push to Itch.io (web)
        run: butler push build/web palp/rat-wars:web
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      # - name: Push to Itch.io (linux)
      #   run: butler push ${{ steps.export.outputs.build_directory }}/linux palp/rat-wars:linux
      #   env:
      #     BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      # - name: Push to Itch.io (windows)
      #   run: butler push ${{ steps.export.outputs.build_directory }}/win palp/rat-wars:win
      #   env:
      #     BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
