on:
  push:
    branches:
      - main
  pull_request:

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: RAT-WARS

jobs:
  export-web:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    name: Web Export
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p dist/web
          godot --headless --export-release "Web" project.godot
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: dist/web
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install rsync
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: dist/web
