name: Export
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  export:
    strategy:
      fail-fast: false
      matrix:
        build:
          - preset: web
            path: build/web
            output: build/web/index.html
            tag: web
          - preset: linux
            path: build/linux
            output: build/linux/RatWars.x86_64
            tag: linux
          - preset: windows
            path: build/windows
            output: build/windows/RatWars.exe
            tag: windows

        # platform: [web, linux, windows]
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.1.3.stable ~/.local/share/godot/export_templates/4.1.3.stable
      - name: "Update Project"
        if: ${{ !cancelled() }}
        timeout-minutes: 1
        continue-on-error: true # we still ignore the timeout, the script is not quit and we run into a timeout
        shell: bash
        run: |
          godot -e --path . -s res://addons/gdUnit4/bin/ProjectScanner.gd --headless --audio-driver Dummy
      - name: Build
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        continue-on-error: true
        run: |
          mkdir -v -p ${{matrix.build.path}}
          godot -v --headless --audio-driver Dummy --export-release "${{matrix.build.preset}}" "${{matrix.build.output}}"
      - name: Set up butler
        if: ${{ !cancelled() }}
        uses: jdno/setup-butler@v1
      - name: Push to Itch.io (${{matrix.build.tag}}))
        if: ${{ !cancelled() }}
        run: butler push ${{matrix.build.path}} palp/rat-wars:${{matrix.build.tag}}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
