on:
  push:

jobs:
  test:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: croconut/godot-tester@v5
        with:
          version: 4.1.3
